[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.setuptools", "gcc"]

[phases.install]
cmds = [
    "python3.12 -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt"
]

[phases.build]

[start]
cmd = "python start.py"
